export enum OperationEvent {
 UPDATE_BALANCE_ACCOUNT_EVENT = "[Operation-API] UPDATE BALANCE ON CURRENT ACCOUNT EVENT",
 REFRESH_EVENT = "[Operation-API] REFRESH LIST OF OPERATIONS EVENT",
 CREATE_TRANSFER_EVENT = "[Operation-API] CREATE TRANSFER EVENT"

}