/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.exalt.exalthexagonalarchikafkakeycloakcustomerapi.domain.avro_beans;
@org.apache.avro.specific.AvroGenerated
public enum CustomerState implements org.apache.avro.generic.GenericEnumSymbol<CustomerState> {
  ACTIVE, ARCHIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CustomerState\",\"namespace\":\"com.exalt.exalthexagonalarchikafkakeycloakcustomerapi.domain.avro_beans\",\"symbols\":[\"ACTIVE\",\"ARCHIVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
