spring:
  # spring boot application name
  application:
    name: ${GATEWAY_SERVICE_PROXY_APP_NAME}
    # disable spring boot logo from log
  main:
    banner-mode: off
  #define routes of the backend microservices
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: ${ALLOWED_CROSS_ORIGIN}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
      routes:
        - id: ${ROUTE1_ID}
          uri: ${ROUTE1_URI}
          predicates:
            - Path=${ROUTE1_PREDICATE}
        - id: ${ROUTE2_ID}
          uri: ${ROUTE2_URI}
          predicates:
            - Path=${ROUTE2_PREDICATE}
        - id: ${ROUTE3_ID}
          uri: ${ROUTE3_URI}
          predicates:
            - Path=${ROUTE3_PREDICATE}
        - id: ${ROUTE4_ID}
          uri: ${ROUTE4_URI}
          predicates:
            - Path=${ROUTE4_PREDICATE}

# actuator for exposing metrics
management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true # enable /actuator/health/liveness and /actuator/health/readiness for K8s
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  # zipkin
  zipkin:
    tracing:
      endpoint: http://grafana-zipkin-traces-distributor:9411/api/v2/spans

# the url to the registration service
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_API_APP_NAME}:${SERVICE_REGISTRY_API_SERVER_PORT}/eureka

server:
  port: ${GATEWAY_SERVICE_PROXY_PORT}