/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.exalt.exalthexagonalarchikafkakeycloakbankaccountapi.domain.avro_beans;
@org.apache.avro.specific.AvroGenerated
public enum AccountState implements org.apache.avro.generic.GenericEnumSymbol<AccountState> {
  CREATED, ACTIVE, SUSPENDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccountState\",\"namespace\":\"com.exalt.exalthexagonalarchikafkakeycloakbankaccountapi.domain.avro_beans\",\"symbols\":[\"CREATED\",\"ACTIVE\",\"SUSPENDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
