services:
  #grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - stack-docker-compose_bank-account-app-net

volumes:
  grafana-storage:
    driver: local

networks:
  stack-docker-compose_bank-account-app-net:
    external: true