spring:
  #application name
  application:
    name: ${CUSTOMER_API_APP_NAME}
    # disable logo in logs
  main:
    banner-mode: off
    # database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOSTNAME}:${DATABASE_HOST_PORT}/${CUSTOMER_API_DB}
    username: ${DATABASE_ROOT_USER}
    password: ${DATABASE_ROOT_PWD}
  # disable JPA auto creation because using flyway
  jpa:
    hibernate:
      ddl-auto: none
  # flyway config
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  # kafka brokers
  kafka:
    bootstrap-servers: http://kafka-server-1:19092,http://kafka-server-2:29092
    # schema registry config to define a common model of event for kafka producer and kafka consumer
    properties:
      schema:
        registry:
          url: http://schema-registry-service:8081
  # security config: urls for Keycloak authentication provider
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}
# clients ids
security:
  oauth2:
    converter:
      keycloak:
        backend-gateway-client-id: ${KEYCLOAK_BACKEND_GATEWAY_CLIENT_ID}
        public-angular-app-client-id: ${KEYCLOAK_ANGULAR_APP_CLIENT_ID}

# kafka topic configuration: duration time and size of message, topic partitions and topic replicas
kafka:
  topic-config:
    name: ${CUSTOMER_TOPIC_NAME}
    retention:
      duration: ${KAFKA_TOPIC_RETENTION_DURATION}

server:
  port: ${CUSTOMER_API_SERVER_PORT}
# atcuator config, to be used by K8s for healthcheck
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true # enable /actuator/health/liveness and /actuator/health/readiness for K8s
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# eureka server for microservices registration (for testing, it will be removed when deploying into k8s)
eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_API_APP_NAME}:${SERVICE_REGISTRY_API_SERVER_PORT}/eureka/

# swagger ui for apis documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

